codecov:
  token: 75b88134-7456-4c8c-9cda-36c35fa35f87

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
