#' Class tskrr
#'
#' The class tskrr represents a two step kernel ridge regression fitting
#' object, and is normally generated by the function \code{\link{tskrr}}.
#' This is a superclass so it should not be instantiated directly.
#'
#' @slot y the matrix with responses
#' @slot k the eigen decomposition of the kernel matrix for the rows
#' @slot lambda.k the lambda value used for k
#' @slot pred the matrix with the predictions
#' @slot has.orig a logical value indicating whether the original kernel
#' matrices are stored in the object.
#' @slot k.orig the original kernel matrix for the rows.
#'
#' @seealso the classes \code{\link{tskrrHomogenous}} and
#' \code{\link{tskrrHeterogenous}} for the actual classes
#'
#' @rdname tskrr-class
#' @name tskrr-class
#' @exportClass tskrr
setOldClass("eigen")

setClass("tskrr",
         slots = c(y = "matrix",
                   k = "eigen",
                   lambda.k = "numeric",
                   pred = "matrix",
                   has.orig = "logical",
                   k.orig = "matrix"),
         prototype = list(y = matrix(0),
                          k = structure(list(vectors = matrix(0),
                                             values = numeric(1)),
                                        class = "eigen"
                                        ),
                          lambda.k = 1e-4,
                          pred = matrix(0),
                          has.orig = FALSE,
                          k.orig = matrix(0)))

validTskrr <- function(object){
  if(!all(is.numeric(object@y),
          is.numeric(object@pred)))
    return("y and pred should be a numeric matrix.")

  else if(length(object@lambda.k) != 1)
    return("lambda.k should be a single value.")

  else
    return(TRUE)
}

setValidity("tskrr", validTskrr)
