#' Class linearFilter
#'
#' The class represents the outcome of a linear filter, and is normally
#' generated by the function \code{\link{linear_filter}}
#'
#' @slot y the original adjacency matrix with responses.
#' @slot alpha a numeric vector with the 4 alpha values of the model.
#' @slot pred a matrix with the predictions
#' @slot mean a numeric vector containing the global mean of \code{y}
#' @slot colmeans a numeric vector containing the column means of \code{y}
#' @slot rowmeans a numeric vector containing the row means of \code{y}.
#'
#' @seealso \code{\link{linear_filter}} for creating a linear filter model,
#' and \code{\link[=getters_linearFilter]{getter fuctions for linearFilter}}.
#'
#' @aliases linearFilter
setClass("linearFilter",
         slots = c(
           y = "matrix",
           alpha = "numeric",
           pred = "matrix",
           mean = "numeric",
           colmeans = "numeric",
           rowmeans = "numeric"
         ))