#' Class tskrr
#'
#' The class tskrr represents a two step kernel ridge regression fitting
#' object, and is normally generated by the function \code{\link{tskrr}}.
#' This is a superclass so it should not be instantiated directly.
#'
#' @slot y an adjacency matrix
#' @slot k an object of class \code{\link[=dataClasses]{gramData}}
#' @slot lambda.k the lambda value used for k
#' @slot pred the matrix with the predictions
#' @slot has.hat a logical value indicating whether the kernel hat matrices
#' are stored in the object.
#' @slot Hk the kernel hat matrix for the rows.
#'
#' @seealso the classes \code{\link{tskrrHomogeneous}} and
#' \code{\link{tskrrHeterogeneous}} for the actual classes.
#'
#' @importFrom utils str
#'
#' @include Class_dataClasses.R
#'
#' @rdname tskrr-class
#' @name tskrr-class
#' @exportClass tskrr


setClass("tskrr",
         slots = c(y = "matrix",
                   k = "gramData",
                   lambda.k = "numeric",
                   pred = "matrix",
                   has.hat = "logical",
                   Hk = "matrix"),
         prototype = list(lambda.k = 1e-4,
                          pred = matrix(0),
                          has.hat = FALSE,
                          Hk = matrix(0)))

validTskrr <- function(object){

  if(!is.numeric(object@pred))
    return("pred should be a numeric matrix.")

  else if(length(object@lambda.k) != 1)
    return("lambda.k should be a single value.")

  else
    return(TRUE)
}

setValidity("tskrr", validTskrr)
################################################
# SHOW METHOD

.show_tskrr <- function(object, homogeneous){
  dims <- paste(dim(object@y), collapse = " x ")
  cat("Dimensions:", dims,"\n")
  cat("Lambda:\n")
  print(lambda(object))

  labs <- labels(object)
  if(homogeneous)
    cat("\nLabels:")
  else
    cat("\nRow Labels:")

  str(labs$k, give.length = FALSE, give.head = FALSE,
      width = getOption("width") - 11)
  if(!homogeneous){
    cat("Col Labels:")
    str(labs$g, give.length = FALSE, give.head = FALSE,
        width = getOption("width") - 11)
  }
}

setMethod("show",
          "tskrr",
          function(object){
            ishomog <- is_homogeneous(object)
            type <- ifelse(ishomog,"Homogeneous","Heterogeneous")
            tl   <- ifelse(ishomog,"----------","------------")
            cat(paste(type,"two-step kernel ridge regression"),
                paste(tl,"--------------------------------",sep="-"),
                sep = "\n")

            .show_tskrr(object, ishomog)

          })

